### ISSUE TITLE
How can I use this library?

### ISSUE THREAD

**Issue by Comdex** [badgerodon/mp3#1]
rt. Thanks.

**Comment by calebdoxsey** [comment]
Hi Comdex, is there anything in particular you are trying to do? This library was put together for a very specific purpose: efficiently slicing & splicing mp3s. It doesn't really have much functionality besides that. Here are a few things you can do: (http://godoc.org/github.com/badgerodon/mp3)

Assuming you have a file:

```
f, err := os.Open("somefile.mp3")
```

You can get its length:

```
duration, err := mp3.Length(f)
```

Cut it into pieces:

```
pieces, err := mp3.Slice(f, time.Second, time.Second*2, time.Second*3)
```

Splice several mp3s into another one:

```
combined, err := mp3.Splice(f, map[time.Duration]io.ReadSeeker{time.Second: someOtherFile})
```

And that's about it. Basically it allows you to manipulate an MP3 file at frame boundaries and skipping ID3 tags.

I gave a talk about this library here: https://www.youtube.com/watch?v=IMYA5PwA8Cs. Though you'll have to skip a bit to get to the meat of it.

**Comment by Comdex** [comment]
Ok. Thanks. I also wan to read information from mp3's ID3 tags

**Comment by calebdoxsey** [comment]
In that case I'd recommend a different library: http://godoc.org/?q=id3

Looks like there are several that can parse id3 tags.
